Repository gausstalk/gausstalk-frontend, pull requests merged in 2022-06, with the labels that each got.

#23 github actions deploy to aks
  .github/workflows/main-to-aks.yml
  manifests/deployment.yaml
  manifests/ingress.yaml
  package-lock.json
  package.json
Labels: feature

#22 Resolve warnings
  package-lock.json
  package.json
  src/components/custom-bottom-nav-bar.js
  src/components/custom-nav-bar.js
  src/components/start.js
  src/index.js
Labels: bug

#24 Signup page
  src/components/auth.js
  src/components/create-user.js
  src/components/logout.js
  src/components/signup.js
  src/index.js
Labels: feature

#25 add privacy policy
  package-lock.json
  src/assets/styles/signup.css
  src/components/custom-nav-bar.js
  src/components/signup.js
Labels: feature

#26 fix api slashes
  src/components/create-user.js
Labels: bug

#28 store user info in session storage
  package-lock.json
  src/components/chat.js
  src/components/custom-nav-bar.js
  src/components/user-context.tsx
Labels: feature

#29 fix login error
  src/components/custom-nav-bar.js
Labels: bug

#31 save name for chat
  src/components/chat.js
  src/components/logout.js
Labels: bug

#33 change profile and text color with hashing and fix date
  src/components/chat.js
Labels: bug, enhancement

#44 add package-lock.json into the repo
  .gitignore
  package-lock.json
Labels: bug

#45 delete devspace files
  devspace.yaml
  devspace_start.sh
Labels: enhancement

#46 add loading
  src/assets/styles/auth.css
  src/assets/styles/start.css
  src/components/auth.js
Labels: enhancement

#47 hide the same username and time for chats
  src/components/chat.js
Labels: enhancement

#59 fix countdown timer bug
  src/components/one-on-one.js
Labels: bug

#60 fix countdown timer deadline
  src/components/one-on-one.js
Labels: bug

#62 fix duplicate chat messages bug
  src/components/chat.js
Labels: bug

#65 fix iOS height not fitting
  src/assets/styles/index.css
Labels: bug

#67 change logo sizes
  public/index.html
  public/logo192.png
  public/manifest.json
  src/assets/images/logo192.png
  src/assets/images/logo512.png
  src/assets/styles/chat.css
  src/components/custom-bottom-nav-bar.js
  src/components/custom-nav-bar.js
Labels: enhancement

#80 fix chat incorrect sender bug
  src/components/chat.js
  src/components/custom-nav-bar.js
Labels: bug

#81 separate component and page
  src/index.js
  src/pages/auth.js
  src/pages/chat.js
  src/pages/contact.js
  src/pages/create-user.js
  src/pages/logout.js
  src/pages/one-on-one.js
  src/pages/signup.js
  src/pages/start.js
Labels: enhancement
